trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  registryServer: 'vueapp.azurecr.io'
  imageName: 'my-vue-app'
  containerAppName: 'my-vue-live-app'
  resourceGroup: 'vue-project-rg'

steps:

- task: Docker@2
  displayName: Build and Push to ACR
  inputs:
    containerRegistry: 'Azure-Docker-Connection'
    repository: '$(imageName)'
    command: buildAndPush
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: AzureCLI@2
  displayName: Debug Container App
  inputs:
    azureSubscription: 'Azure-Cloud-Connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az extension add --name containerapp --upgrade --yes

      echo "==== ACCOUNT ===="
      az account show

      echo "==== GROUP ===="
      az group show --name vue-project-rg

      echo "==== RESOURCE ===="
      az resource list \
        --resource-group vue-project-rg \
        --resource-type Microsoft.App/containerApps \
        -o table

      echo "==== CONTAINER APPS ===="
      az containerapp list \
        --resource-group vue-project-rg \
        -o table